#!/bin/sh

HOST=$1
BASEDIR=$2
NUM=$3
port=6000
Port=6002
LIBPATH=/home/username/rcss/teams/rc2023/Damavand/lib
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

teamname="Damavand"

player="/home/username/rcss/teams/rc2023/Damavand/sample_player"
coach="/home/username/rcss/teams/rc2023/Damavand/sample_coach"

config="/home/username/rcss/teams/rc2023/Damavand/player.conf"
config_dir="/home/username/rcss/teams/rc2023/Damavand/formations-dt"
coach_config="/home/username/rcss/teams/rc2023/Damavand/coach.conf"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname} -p ${port}"

coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname} -p ${Port}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
